### ISSUE TITLE
[Marketplace] Kick off of the main modules

### ISSUE THREAD

**Issue by karntrehan** [COMPASS-DPG/course-manager#5]
- [x] Finalize DB modelling
- [x] API Requirements
- [x] Integration of services (plan)
- [x] Update repos with boiler plate for each service
- [x] Add subtasks for implementation

**Comment by karntrehan** [comment]
APIs for course manager built have been dev tested. 

Course portal APIs to be started - Tracked in #6

**Comment by L-Narayana** [comment]
PRs have been raised for the APIs. Some APIs remaining in the course portal side (Sanchit). Pending tasks would be closed by EOD
